name: Initialize Environment
description: Checks out code and installs Yarn

branding:
  icon: play
  color: green

inputs:
  package-name:
    required: false
    default: null
    description: Name of the workspace/package you're initializing

  install-deps:
    required: false
    default: true
    description: "Should dependencies be installed? (default: true)"

  playwright:
    required: false
    default: false
    description: Should run the Playwright installation command

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Use Node.js 💻
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: yarn

    - name: Install Dependencies (Focused)
      if: inputs.workspace-name != null && inputs.install-deps
      run: yarn workspaces focus ${{ inputs.package-name }}
      shell: bash

    - name: Install Dependencies (General)
      if: inputs.package-name == null && inputs.install-deps
      run: yarn install --immutable
      shell: bash

    - name: Install Playwright
      if: inputs.playwright == 'true' && inputs.install-deps
      run: yarn playwright install --with-deps
      shell: bash
