name: Initialize Environment
description: Checks out code and installs Yarn

branding:
  icon: play
  color: green

inputs:
  package-name:
    required: false
    default: ''
    description: Name of the workspace/package you're initializing

  install-deps:
    required: false
    default: true
    description: "Should dependencies be installed? (default: true)"

  playwright:
    required: false
    default: false
    description: Should run the Playwright installation command

  shell:
    required: true
    description: What shell to use

defaults:
  runs:
    shell: ${{ inputs.shell }}

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable

    - name: Use Node.js 💻
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: yarn

    - name: Install Dependencies (Focused)
      if: inputs.package-name != '' && inputs.install-deps == 'true'
      run: yarn workspaces focus ${{ inputs.package-name }}

    - name: Install Dependencies (General)
      if: inputs.package-name == '' && inputs.install-deps == 'true'
      run: yarn install --immutable

    - name: Install Playwright
      if: inputs.playwright == 'true' && inputs.install-deps == 'true'
      run: yarn workspaces foreach -A --include ${{ inputs.package-name }} run playwright install --with-deps
