approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 4320 # 3 days

# exempt our own first-party packages
npmPreapprovedPackages:
  - js-slang
  - '@sourceacademy/conductor'

# Supported from Yarn 4.10.0 onwards
# https://yarnpkg.com/features/catalogs
# Define here to avoid duplications
catalog:
  '@sourceacademy/conductor': ^0.7.0
  js-slang: ^1.0.94
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  vitest: 4.1.10
  '@vitest/browser-playwright': 4.1.10
  '@vitest/coverage-v8': 4.1.10
  '@vitest/ui': 4.1.10
  '@vitest/eslint-plugin': ^1.6.20
  typescript: ^6.0.3
