/** encapsulates 3D point with RGB values */
export type Point = {
  x: number;
  y: number;
  z: number;
  color: [r: number, g: number, b: number, t: number];
};
/** a function that takes in number from 0 to 1 and returns a Point */
export type CurveFunction = (t: number) => Point;
/**
 * a function that specifies additional rendering information when taking in
 * a CurveFunction and returns a ShapeDrawn based on its specifications.
 */
export type RenderFunction = (func: CurveFunction) => ShapeDrawn;
/** a function that takes in CurveFunction and returns a tranformed CurveFunction */
export type CurveTransformer = (c: CurveFunction) => CurveFunction;
/**
 * the return type of the curve generated by the source code in workspace.
 * WebGLCanvas in Curves tab captures the return value and calls its init function.
 */
export type ShapeDrawn = {
  /** string to be printed in the REPL */
  toReplString: () => string;
  /** a series of actions to perform to draw on the given canvas */
  init: (canvas: HTMLCanvasElement) => void;
};
export type ProgramInfo = {
  program: WebGLProgram;
  attribLocations: {
    vertexPosition: number;
    vertexColor: number;
  };
  uniformLocations: {
    projectionMatrix: WebGLUniformLocation | null;
    modelViewMatrix: WebGLUniformLocation | null;
  };
};
export type BufferInfo = {
  cubeBuffer: WebGLBuffer | null;
  curveBuffer: WebGLBuffer | null;
  curveColorBuffer: WebGLBuffer | null;
};
