declare module "curve" {
    export const arc: Curve;
    export function b_of(pt: Point): number;
    export function compose(...transformers: CurveTransformer[]): CurveTransformer;
    export function connect_ends(curve1: Curve, curve2: Curve): Curve;
    export function connect_rigidly(curve1: Curve, curve2: Curve): Curve;
    export function g_of(pt: Point): number;
    export const invert: CurveTransformer;
    export function make_3D_color_point(x: number, y: number, z: number, r: number, g: number, b: number): Point;
    export function make_3D_point(x: number, y: number, z: number): Point;
    export function make_color_point(x: number, y: number, r: number, g: number, b: number): Point;
    export function make_point(x: number, y: number): Point;
    export const put_in_standard_position: CurveTransformer;
    export function rainbow(repeats: number, phase: number): CurveTransformer;
    export function r_of(pt: Point): number;
    export function rotate_around_origin(a: number): CurveTransformer;
    export function rotate_around_origin_3D(a: number, b: number, c: number): CurveTransformer;
    export function scale(x: number, y: number, z: number): CurveTransformer;
    export function scale_proportional(s: number): CurveTransformer;
    export function translate(x0: number, y0: number, z0: number): CurveTransformer;
    export const unit_circle: Curve;
    export const unit_line: Curve;
    export function unit_line_at(y: number): Curve;
    export function x_of(pt: Point): number;
    export function y_of(pt: Point): number;
    export function z_of(pt: Point): number;
    export function animate_3D_curve(duration: number, fps: number, drawer: RenderFunction, func: CurveAnimation): AnimatedCurve;
    export function animate_curve(duration: number, fps: number, drawer: RenderFunction, func: CurveAnimation): AnimatedCurve;
    export function draw_3D_connected(numPoints: number): RenderFunction;
    export function draw_3D_connected_full_view(numPoints: number): RenderFunction;
    export function draw_3D_connected_full_view_proportional(numPoints: number): RenderFunction;
    export function draw_3D_points(numPoints: number): RenderFunction;
    export function draw_3D_points_full_view(numPoints: number): RenderFunction;
    export function draw_3D_points_full_view_proportional(numPoints: number): RenderFunction;
    export function draw_connected(numPoints: number): RenderFunction;
    export function draw_connected_full_view(numPoints: number): RenderFunction;
    export function draw_connected_full_view_proportional(numPoints: number): RenderFunction;
    export function draw_points(numPoints: number): RenderFunction;
    export function draw_points_full_view(numPoints: number): RenderFunction;
    export function draw_points_full_view_proportional(numPoints: number): RenderFunction;
    export type RenderFunction = (func: Curve) => CurveDrawn;
    export type Curve = (u: number) => Point;
}