export {
  make_vector,
  make_parameterized_vector,
  derivative,
  threepointStencilDerivative,
  x_of,
  y_of,
  z_of,
  stringify_vector,
  display_field,
  display_field_curve,
  display_field_surface,
  add,
  simulate_body_in_field,
} from './functions'
