/**
 * Reusable React Components and styling utilities designed for use with SA Module Tabs
 * @module Tabs
 * @title Tabs Library
 */

// This file is necessary so that the documentation generated by typedoc comes out in
// the correct format. Don't actually import anything from this file
// (not that you should be able to)

export { default as AnimationCanvas, type AnimCanvasProps } from './AnimationCanvas';
export { default as AnimationError } from './AnimationError';
export { default as AutoLoopSwitch, type AutoLoopSwitchProps } from './AutoLoopSwitch';
export { default as ButtonComponent, type ButtonComponentProps } from './ButtonComponent';
export * from './css_constants';
export { default as ModalDiv, type ModalProps } from './ModalDiv';
export { default as MultiItemDisplay, type MultiItemDisplayProps } from './MultiItemDisplay';
export { default as NumberSelector, type NumberSelectorProps } from './NumberSelector';
export { default as PlayButton, type PlayButtonProps } from './PlayButton';
export { useAnimation, type AnimationOptions, type AnimationHookResult } from './useAnimation';
export * from './utils';
export { default as WebGLCanvas, type WebGLCanvasProps } from './WebGLCanvas';
