name: Package Info
description: Gets which packages are currently present in the repository

outputs:
  libs:
    description: The list of library packages present
  bundles:
    description: The list of bundles packages present
  tabs:
    description: The list of tabs packages present
  devserver:
    description: Information for the devserver
  docserver:
    description: Information for the docserver
  workflows:
    description: Boolean value. True if there were changes to workflow files, false otherwise.

runs:
  using: node20
  main: ../../dist/info.js
